package = "ssd"
version = "0.9"
date = "19 Junho 2020"
license = "GPL"
depends = "terrame (>= 2.0)"
title = "ssd - Spatial System Dynamics"
authors = "Andre F. Amancio and Tiago G. S. Carneiro"
contact = "andre.amancio@ufop.edu.br, tiago@edu.ufop.br"
content = "Implements the operators Flow and Connector to Spatial System Dynamics Extension"